version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: boulderify-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command:
      - --quiet

  minio:
    image: minio/minio:latest
    container_name: boulderify-minio
    restart: unless-stopped
    ports:
      - "9000:9000" # API
      - "9001:9001" # Console
    volumes:
      - minio-data:/data
      - ./minio-init:/docker-entrypoint-init.d
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_BROWSER_CORS_ALLOW_ORIGIN: "*"
    entrypoint: /bin/sh
    command: -c 'minio server /data --console-address :9001 & /docker-entrypoint-init.d/init.sh && wait'

  backend:
    build: ./backend
    container_name: boulderify-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/boulderify
    depends_on:
      - mongo
      - minio

volumes:
  mongo-data:
  minio-data: 